# Generated by Django 4.2.6 on 2023-10-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
