# Generated by Django 4.2.6 on 2023-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientLogo',
            field=models.ImageField(default='default_logo.png', upload_to='company_logos'),
        ),
    ]
