# Generated by Django 4.2.6 on 2023-10-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_usersettings_rename_uniqueid_client_clientid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.DeleteModel(
            name='InvoiceLineItem',
        ),
    ]
