# Generated by Django 4.2.6 on 2023-10-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0009_invoice_user_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='paymentTerms',
            field=models.CharField(blank=True, choices=[('7 Days', '7 Days'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], max_length=50, null=True),
        ),
    ]
